### ISSUE TITLE
Swagger docs build fail in CI

### ISSUE THREAD

**Issue by enricorotundo** [filecoin-project/bacalhau#1366]
```
#!/bin/bash -eo pipefail
make swagger-docs
comm: file 1 is not in sorted order
comm: input is not in sorted order
Building swagger docs...
swag fmt --exclude "testground" -g "pkg/publicapi/server.go" && \
swag init --parseDependency --exclude "testground" --markdownFiles docs/swagger -g "pkg/publicapi/server.go"
2022/11/24 13:54:24 Generate swagger docs....
2022/11/24 13:54:24 Generate general API Info, search dir:./
panic: interface conversion: interface {} is string, not int

goroutine 1 [running]:
github.com/swaggo/swag.(*PackageDefinitions).evaluateConstValue(0xc006cff540, 0xc027f06090?, 0xc0079c8800?, {0xa5b4a0?, 0xc006d01620?}, {0xa59a40, 0xc000141840}, 0x58?)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/package.go:132 +0x113f
github.com/swaggo/swag.(*PackagesDefinitions).EvaluateConstValue(0xc0287c9698?, 0xc006cff540, 0xc017377340, 0x0)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:282 +0x19d
github.com/swaggo/swag.(*PackagesDefinitions).evaluateAllConstVariables(...)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:265
github.com/swaggo/swag.(*PackagesDefinitions).ParseTypes(0xc000141840)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/packages.go:110 +0x254
github.com/swaggo/swag.(*Parser).ParseAPIMultiSearchDir(0xc000204000, {0xc0001c1ff0?, 0x1?, 0x0?}, {0x7ffe6a33febe?, 0x17?}, 0x64)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/parser.go:375 +0x3bf
github.com/swaggo/swag/gen.(*Gen).Build(0xc0001cf8f0, 0xc0001ca2a0)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/gen/gen.go:182 +0x637
main.initAction(0xc0001f2780?)
	/home/circleci/.go_workspace/pkg/mod/github.com/swaggo/swag@v1.8.8/cmd/swag/main.go:158 +0x7bd
github.com/urfave/cli/v2.(*Comm
```

https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/2316/workflows/64c74e6b-ec95-4c6e-8a72-88b299f9af3c/jobs/18198

**Comment by enricorotundo** [comment]
may be related to https://github.com/swaggo/swag/issues/1392

**Comment by enricorotundo** [comment]
it’s a problem with swag version v1.8.8…. v1.8.7 should work fine. Will pin the swag version used by CI and update the GH options making build_swagger a requirment

**Comment by simonwo** [comment]
Can we make the swagger build part of dev branches as well? So people can't break it pre-merge
