### ISSUE TITLE
Tests failing locally due to concurrency?

### ISSUE THREAD

**Issue by aronchick** [filecoin-project/bacalhau#860]
```
=== RUN   TestDeterministicVerifierSuite/TestDeterministicVerifier
15:47:13.942 | ERR eventhandler/chained_handlers.go:104 > {"EventName":"Bid","ShardID":"71558462-e816-44e3-b853-311f5bee195f_1","SourceNodeID":"QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb","TargetNodeID":"","Duration":0,"HandlerError":"cannot update shard state to Bidding as current state is Waiting. [NodeID: QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb, ShardID: 71558462-e816-44e3-b853-311f5bee195f_1]"} [NodeID:QmU9gGWf]
15:47:13.942 | ERR libp2p/libp2p.go:388 > error in handle event: cannot update shard state to Bidding as current state is Waiting. [NodeID: QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb, ShardID: 71558462-e816-44e3-b853-311f5bee195f_1]
{APIVersion: JobID:71558462-e816-44e3-b853-311f5bee195f ShardIndex:1 ClientID: SourceNodeID:QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb TargetNodeID: EventName:Bid Spec:{Engine:engineUnknown EngineName: Verifier:verifierUnknown VerifierName: Publisher:publisherUnknown PublisherName: Docker:{Image: Entrypoint:[] EnvironmentVariables:[] WorkingDirectory:} Language:{Language: LanguageVersion: Deterministic:false Context:{StorageSource:storageSourceUnknown StorageSourceName: Name: CID: URL: Path: Metadata:map[]} Command: ProgramPath: RequirementsPath:} Resources:{CPU: Memory: Disk: GPU:} Inputs:[] Contexts:[] Outputs:[] Annotations:[] Sharding:{GlobPattern: BatchSize:0 BasePath:} DoNotTrack:false} JobExecutionPlan:{TotalShards:0} Deal:{Concurrency:0 Confidence:0 MinBids:0} Status: VerificationProposal:[] VerificationResult:{Complete:false Result:false} PublishedResult:{StorageSource:storageSourceUnknown StorageSourceName: Name: CID: URL: Path: Metadata:map[]} EventTime:2022-10-10 15:47:13.930901 -0700 PDT SenderPublicKey:[8 0 18 166 2 48 130 1 34 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 130 1 15 0 48 130 1 10 2 130 1 1 0 242 137 168 80 96 244 153 166 193 59 160 254 178 246 147 31 113 25 27 84 172 194 17 54 68 45 217 237 15 18 100 90 84 74 252 51 89 96 53 164 62 30 211 98 171 109 134 108 240 229 118 60 230 42 29 59 26 220 178 136 224 94 233 17 216 190 151 88 34 114 102 174 101 231 52 156 2 184 111 8 100 104 98 134 77 2 51 62 194 11 112 101 0 158 2 122 184 121 97 163 28 208 151 243 213 104 26 22 35 121 21 21 23 30 53 17 242 130 211 200 98 90 177 228 235 226 211 233 157 160 142 72 176 107 155 70 127 172 228 137 108 18 56 214 94 90 36 177 109 223 47 40 52 64 57 185 46 251 219 141 241 50 10 138 248 66 237 121 33 246 68 204 141 72 62 88 37 89 19 103 136 232 94 55 46 89 191 105 146 35 62 35 172 0 141 226 38 127 147 45 142 130 60 220 129 112 84 144 54 233 129 5 7 94 247 73 91 127 204 207 134 75 173 73 184 245 96 95 0 82 16 246 50 79 171 229 176 102 15 162 161 36 43 195 115 81 251 172 250 118 42 18 125 129 6 179 2 3 1 0 1] RunOutput:<nil>} [NodeID:QmU9gGWf]
15:47:13.943 | ERR eventhandler/chained_handlers.go:104 > {"EventName":"Bid","ShardID":"71558462-e816-44e3-b853-311f5bee195f_0","SourceNodeID":"QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb","TargetNodeID":"","Duration":0,"HandlerError":"cannot update shard state to Bidding as current state is Waiting. [NodeID: QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb, ShardID: 71558462-e816-44e3-b853-311f5bee195f_0]"} [NodeID:QmU9gGWf]
15:47:13.943 | ERR libp2p/libp2p.go:388 > error in handle event: cannot update shard state to Bidding as current state is Waiting. [NodeID: QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb, ShardID: 71558462-e816-44e3-b853-311f5bee195f_0]
{APIVersion: JobID:71558462-e816-44e3-b853-311f5bee195f ShardIndex:0 ClientID: SourceNodeID:QmfAoyqQthaV5WbNtVnfYUdZ4jGUvS4RcGogpxogZhX5vb TargetNodeID: EventName:Bid Spec:{Engine:engineUnknown EngineName: Verifier:verifierUnknown VerifierName: Publisher:publisherUnknown PublisherName: Docker:{Image: Entrypoint:[] EnvironmentVariables:[] WorkingDirectory:} Language:{Language: LanguageVersion: Deterministic:false Context:{StorageSource:storageSourceUnknown StorageSourceName: Name: CID: URL: Path: Metadata:map[]} Command: ProgramPath: RequirementsPath:} Resources:{CPU: Memory: Disk: GPU:} Inputs:[] Contexts:[] Outputs:[] Annotations:[] Sharding:{GlobPattern: BatchSize:0 BasePath:} DoNotTrack:false} JobExecutionPlan:{TotalShards:0} Deal:{Concurrency:0 Confidence:0 MinBids:0} Status: VerificationProposal:[] VerificationResult:{Complete:false Result:false} PublishedResult:{StorageSource:storageSourceUnknown StorageSourceName: Name: CID: URL: Path: Metadata:map[]} EventTime:2022-10-10 15:47:13.930906 -0700 PDT SenderPublicKey:[8 0 18 166 2 48 130 1 34 48 13 6 9 42 134 72 134 247 13 1 1 1 5 0 3 130 1 15 0 48 130 1 10 2 130 1 1 0 242 137 168 80 96 244 153 166 193 59 160 254 178 246 147 31 113 25 27 84 172 194 17 54 68 45 217 237 15 18 100 90 84 74 252 51 89 96 53 164 62 30 211 98 171 109 134 108 240 229 118 60 230 42 29 59 26 220 178 136 224 94 233 17 216 190 151 88 34 114 102 174 101 231 52 156 2 184 111 8 100 104 98 134 77 2 51 62 194 11 112 101 0 158 2 122 184 121 97 163 28 208 151 243 213 104 26 22 35 121 21 21 23 30 53 17 242 130 211 200 98 90 177 228 235 226 211 233 157 160 142 72 176 107 155 70 127 172 228 137 108 18 56 214 94 90 36 177 109 223 47 40 52 64 57 185 46 251 219 141 241 50 10 138 248 66 237 121 33 246 68 204 141 72 62 88 37 89 19 103 136 232 94 55 46 89 191 105 146 35 62 35 172 0 141 226 38 127 147 45 142 130 60 220 129 112 84 144 54 233 129 5 7 94 247 73 91 127 204 207 134 75 173 73 184 245 96 95 0 82 16 246 50 79 171 229 176 102 15 162 161 36 43 195 115 81 251 172 250 118 42 18 125 129 6 179 2 3 1 0 1] RunOutput:<nil>} [NodeID:QmU9gGWf]
fatal error: concurrent map writes

goroutine 66238 [running]:
runtime.throw({0x102be4264?, 0x14003cde4e0?})
	/opt/homebrew/opt/go@1.18/libexec/src/runtime/panic.go:992 +0x50 fp=0x1400246fcc0 sp=0x1400246fc90 pc=0x100a4d3a0
runtime.mapassign_fast64(0x1033f1520?, 0x14004b23400?, 0x1)
	/opt/homebrew/opt/go@1.18/libexec/src/runtime/map_fast64.go:102 +0x2e0 fp=0x1400246fd00 sp=0x1400246fcc0 pc=0x100a25ed0
github.com/filecoin-project/bacalhau/pkg/publisher.(*MappedPublisherProvider).GetPublisher(0x14004c06d60, {0x10386b1f8, 0x14004665e30}, 0x14006f36300?)
	/Users/daaronch/code/bacalhau/pkg/publisher/publisher_provider.go:39 +0xb0 fp=0x1400246fd70 sp=0x1400246fd00 pc=0x1011a73f0
github.com/filecoin-project/bacalhau/pkg/computenode.(*ComputeNode).PublishShard(0x14004920400, {0x10386b1f8, 0x14004665e30}, {0x14006f36300?, 0x102a6b5a8?})
	/Users/daaronch/code/bacalhau/pkg/computenode/computenode.go:551 +0xa8 fp=0x1400246fef0 sp=0x1400246fd70 pc=0x1011aab78
github.com/filecoin-project/bacalhau/pkg/computenode.publishingToRequesterState({0x10386b1f8, 0x14006b93aa0}, 0x140053044d0)
	/Users/daaronch/code/bacalhau/pkg/computenode/shard_fsm.go:462 +0x130 fp=0x1400246ff90 sp=0x1400246fef0 pc=0x1011af000
github.com/filecoin-project/bacalhau/pkg/computenode.(*shardStateMachine).Run(...)
	/Users/daaronch/code/bacalhau/pkg/computenode/shard_fsm.go:254
github.com/filecoin-project/bacalhau/pkg/computenode.(*shardStateMachineManager).StartShardStateIfNecessary.func1()
	/Users/daaronch/code/bacalhau/pkg/computenode/shard_fsm.go:141 +0x4c fp=0x1400246ffd0 sp=0x1400246ff90 pc=0x1011ace3c
runtime.goexit()
	/opt/homebrew/opt/go@1.18/libexec/src/runtime/asm_arm64.s:1270 +0x4 fp=0x1400246ffd0 sp=0x1400246ffd0 pc=0x100a82bf4
created by github.com/filecoin-project/bacalhau/pkg/computenode.(*shardStateMachineManager).StartShardStateIfNecessary
	/Users/daaronch/code/bacalhau/pkg/computenode/shard_fsm.go:140 +0x37c

goroutine 1 [chan receive]:
testing.(*T).Run(0x140006ca9c0, {0x102bfd47e?, 0xb4a54878b857?}, 0x10383f798)
	/opt/homebrew/opt/go@1.18/libexec/src/testing/testing.go:1487 +0x314
testing.runTests.func1(0x0?)
	/opt/homebrew/opt/go@1.18/libexec/src/testing/testing.go:1839 +0x74
testing.tRunner(0x140006ca9c0, 0x140002afcb8)
	/opt/homebrew/opt/go@1.18/libexec/src/testing/testing.go:1439 +0x110
testing.runTests(0x140011e2820?, {0x104a60a40, 0xb, 0xb}, {0xb200000000000000?, 0x100a21560?, 0x104d018c0?})
	/opt/homebrew/opt/go@1.18/libexec/src/testing/testing.go:1837 +0x3f0
testing.(*M).Run(0x140011e2820)
	/opt/homebrew/opt/go@1.18/libexec/src/testing/testing.go:1719 +0x500
main.main()
	_testmain.go:67 +0x1d0

goroutine 35 [select]:
io.(*pipe).read(0x1400041a540, {0x14003458001, 0xdff, 0x400?})
	/opt/homebrew/opt/go@1.18/libexec/src/io/pipe.go:57 +0x84
io.(*PipeReader).Read(0x0?, {0x14003458001?, 0x1400363fe68?, 0x100c6163c?})
	/opt/homebrew/opt/go@1.18/libexec/src/io/pipe.go:136 +0x28
encoding/json.(*Decoder).refill(0x140003752c0)
	/opt/homebrew/opt/go@1.18/libexec/src/encoding/json/stream.go:165 +0x174
encoding/json.(*Decoder).readValue(0x140003752c0)
	/opt/homebrew/opt/go@1.18/libexec/src/encoding/json/stream.go:140 +0xa0
encoding/json.(*Decoder).Decode(0x140003752c0, {0x10338ea60, 0x1400087bfb0})
	/opt/homebrew/opt/go@1.18/libexec/src/encoding/json/stream.go:63 +0x64
github.com/filecoin-project/bacalhau/pkg/system.jsonLogger.func1({0x103853ad8?, 0x140004222c0})
	/Users/daaronch/code/bacalhau/pkg/system/tracer.go:227 +0x8c
created by github.com/filecoin-project/bacalhau/pkg/system.jsonLogger
	/Users/daaronch/code/bacalhau/pkg/system/tracer.go:222 +0x188

goroutine 6 [select]:
github.com/ipfs/go-log/writer.(*MirrorWriter).logRoutine(0x140003e21e0)
	/Users/daaronch/code/bacalhau/vendor/github.com/ipfs/go-log/writer/writer.go:71 +0xb8
created by github.com/ipfs/go-log/writer.NewMirrorWriter
	/Users/daaronch/code/bacalhau/vendor/github.com/ipfs/go-log/writer/writer.go:36 +0xd8
```

**Comment by binocarlos** [comment]
This is the [publishersInstalledCache](https://github.com/filecoin-project/bacalhau/blob/main/pkg/publisher/publisher_provider.go#L39) that needs a mutex
