### ISSUE TITLE
Potential concurrent map writes with `JobNodeState.Shards`

### ISSUE THREAD

**Issue by wjam** [filecoin-project/bacalhau#967]
A test run managed to end in failure due to fatal error: concurrent map writes, with this line at the top of the list: 

https://github.com/filecoin-project/bacalhau/blob/a8c764d4343862b8d5e1a15405190779962f6db5/pkg/job/state.go#L339

**Comment by wjam** [comment]
https://circleci.com/api/v1.1/project/github/filecoin-project/bacalhau/9555/output/108/0?file=true&allocation-id=635a7a96d999f87f510bf7bb-0-build%2FT2IZ12TB

```
fatal error: concurrent map iteration and map write

goroutine 109881 [running]:
runtime.throw({0x2433176?, 0x0?})
	/usr/local/go/src/runtime/panic.go:992 +0x71 fp=0xc0092ef800 sp=0xc0092ef7d0 pc=0x438ab1
runtime.mapiternext(0xc0092ef9d8?)
	/usr/local/go/src/runtime/map.go:871 +0x4eb fp=0xc0092ef870 sp=0xc0092ef800 pc=0x41036b
github.com/filecoin-project/bacalhau/pkg/job.FlattenShardStates(...)
	/home/circleci/repo/pkg/job/state.go:339
github.com/filecoin-project/bacalhau/pkg/job.HasShardReachedCapacity({0x291c7e0?, 0xc0097b5c50?}, 0xc0061a1800, {0xc007378db0?}, 0x24?)
	/home/circleci/repo/pkg/job/state.go:389 +0x592 fp=0xc0092efd58 sp=0xc0092ef870 pc=0xb887d2
github.com/filecoin-project/bacalhau/pkg/computenode.processBidJob({0x291c7e0?, 0xc006731dd0?}, {0xc0094f1700, 0xc0065ebeb0?, 0xc0034b2ea0?}, 0xc0065ebf88?, 0xc001ddee00)
	/home/circleci/repo/pkg/computenode/computenode.go:219 +0x272 fp=0xc0092efe30 sp=0xc0092efd58 pc=0xb8fdf2
github.com/filecoin-project/bacalhau/pkg/computenode.(*ComputeNode).controlLoopBidOnJobs(0xc001ddee00, {0x291c7e0, 0xc006731dd0})
	/home/circleci/repo/pkg/computenode/computenode.go:189 +0x17d fp=0xc0092efed8 sp=0xc0092efe30 pc=0xb8fa9d
github.com/filecoin-project/bacalhau/pkg/computenode.(*ComputeNode).controlLoopSetup(0xc001ddee00, {0x291c7e0, 0xc008608300}, 0xc007bfc990?)
	/home/circleci/repo/pkg/computenode/computenode.go:161 +0x19a fp=0xc0092effb0 sp=0xc0092efed8 pc=0xb8f77a
github.com/filecoin-project/bacalhau/pkg/computenode.NewComputeNode.func2()
	/home/circleci/repo/pkg/computenode/computenode.go:89 +0x32 fp=0xc0092effe0 sp=0xc0092effb0 pc=0xb8f032
runtime.goexit()
	/usr/local/go/src/runtime/asm_amd64.s:1571 +0x1 fp=0xc0092effe8 sp=0xc0092effe0 pc=0x46c2a1
created by github.com/filecoin-project/bacalhau/pkg/computenode.NewComputeNode
	/home/circleci/repo/pkg/computenode/computenode.go:89 +0x294
```

**Comment by wjam** [comment]
Same issue reoccurred
https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/1793/workflows/d73f037b-a437-49a5-bc74-56d149f6ff82/jobs/11190

```
fatal error: concurrent map iteration and map write

goroutine 46041 [running]:
github.com/filecoin-project/bacalhau/pkg/job.GetStatesForShardIndex(...)
	/home/circleci/repo/pkg/job/state.go:306
github.com/filecoin-project/bacalhau/pkg/job.(*StateResolver).CheckShardStates(0xc0033d2660, {0x2974160?, 0xc005bc50b0?}, {0xc003efbb00?, 0x1?}, 0xc002b69df0)
	/home/circleci/repo/pkg/job/state.go:278 +0x4e9
github.com/filecoin-project/bacalhau/pkg/verifier/noop.(*NoopVerifier).IsExecutionComplete(0xc001336150?, {0x2974160?, 0xc005bc50b0?}, {0xc003efbb00?, 0x22a2580?})
	/home/circleci/repo/pkg/verifier/noop/verifier.go:80 +0x47
github.com/filecoin-project/bacalhau/pkg/requesternode.(*RequesterNode).verifyShard(0xc0054cb960, {0x2974160, 0xc005bc50b0}, {0xc003efbb00?, 0x406a50?})
	/home/circleci/repo/pkg/requesternode/requesternode.go:188 +0xb0
github.com/filecoin-project/bacalhau/pkg/requesternode.verifyingResultsState({0x2974160, 0xc005bc50b0}, 0xc006448b90)
	/home/circleci/repo/pkg/requesternode/shard_fsm.go:353 +0x65
github.com/filecoin-project/bacalhau/pkg/requesternode.(*shardStateMachine).run(...)
	/home/circleci/repo/pkg/requesternode/shard_fsm.go:162
github.com/filecoin-project/bacalhau/pkg/requesternode.(*shardStateMachineManager).startShardsState.func1()
	/home/circleci/repo/pkg/requesternode/shard_fsm.go:112 +0x3d
created by github.com/filecoin-project/bacalhau/pkg/requesternode.(*shardStateMachineManager).startShardsState
	/home/circleci/repo/pkg/requesternode/shard_fsm.go:111 +0x37b
```

**Comment by wjam** [comment]
Still happening: https://app.circleci.com/pipelines/github/filecoin-project/bacalhau/2113/workflows/913700bd-91d2-4a2d-950f-2a781e4ef920/jobs/15333

**Comment by wjam** [comment]
Haven't seen this flake in a while so closing
